<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fal_online_media_connector"
 *
 * Auto generated by Extension Builder 2014-08-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Youtube',
	'description' => '',
	'category' => 'misc',
	'author' => 'Frans Saris',
	'author_email' => 'franssaris@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'clearCacheOnLoad' => 1,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.4 - 6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);